export const rootPathnames = {
  CURRENT: "",
  CREATE_PROJECT: "/register",
  EDIT_PROJECT: "/edit-project",
  PROJECTS_LIST: "/",
  PROJECT: "/profile",
  CART: "/cart",
  FEED: "/feed",
  POTS: "/pots",
  pot: "/pot",
  DEPLOY_POT: "/deploy",
  DONORS: "/donors",
  LIST: "/lists",
  PROFILE: "/profile",
  CAMPAIGNS: "/campaigns",
  EDIT_PROFILE: "/editprofile",
};
